spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/spring_security
    username: springsecurityuser
    password: spring-security
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: spring_security_lab